version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  commands:
    - pip install uv
    - uv sync --frozen
    - git fetch --unshallow
    - .venv/bin/python -m sphinx -T -b html -d docs/_build/doctrees -D language=en docs $READTHEDOCS_OUTPUT/html
sphinx:
 configuration: "docs/conf.py"
