---
volumes:
  a3m-pipeline-data:
    name: "a3m-pipeline-data"
services:
  a3m:
    build:
      context: "."
    volumes:
      - ".:/a3m"
      - "a3m-pipeline-data:/home/a3m/.local/share/a3m:rw"
    ports:
      - "52000:7000"
