---
version: "2.4"

volumes:

  a3m-pipeline-data:
    name: "a3m-pipeline-data"

services:

  a3m:
    build:
      context: "."
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        REQUIREMENTS: ${REQUIREMENTS:-/a3m/requirements-dev.txt}
        DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-a3m.settings.common}
    environment:
      A3M_PROMETHEUS_BIND_PORT: "7999"
      A3M_PROMETHEUS_BIND_ADDRESS: "0.0.0.0"
    volumes:
      - ".:/a3m"
      - "a3m-pipeline-data:/home/a3m/.local/share/a3m:rw"
    ports:
      - "52000:7000"
