# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: a3m.proto
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="a3m.proto",
    package="a3m",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=b'\n\ta3m.proto\x12\x03\x61\x33m"*\n\rSubmitRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t"\x19\n\x0bSubmitReply\x12\n\n\x02id\x18\x01 \x01(\t"\x1b\n\rStatusRequest\x12\n\n\x02id\x18\x01 \x01(\t"1\n\x0bStatusReply\x12"\n\x06status\x18\x01 \x01(\x0e\x32\x12.a3m.PackageStatus*^\n\rPackageStatus\x12\n\n\x06\x46\x41ILED\x10\x00\x12\x0c\n\x08REJECTED\x10\x01\x12\x0c\n\x08\x43OMPLETE\x10\x02\x12\x0e\n\nPROCESSING\x10\x03\x12\x15\n\x11\x41WAITING_DECISION\x10\x04\x32n\n\x08Transfer\x12\x30\n\x06Submit\x12\x12.a3m.SubmitRequest\x1a\x10.a3m.SubmitReply"\x00\x12\x30\n\x06Status\x12\x12.a3m.StatusRequest\x1a\x10.a3m.StatusReply"\x00\x62\x06proto3',
)

_PACKAGESTATUS = _descriptor.EnumDescriptor(
    name="PackageStatus",
    full_name="a3m.PackageStatus",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="FAILED", index=0, number=0, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="REJECTED", index=1, number=1, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="COMPLETE", index=2, number=2, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="PROCESSING", index=3, number=3, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="AWAITING_DECISION",
            index=4,
            number=4,
            serialized_options=None,
            type=None,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=169,
    serialized_end=263,
)
_sym_db.RegisterEnumDescriptor(_PACKAGESTATUS)

PackageStatus = enum_type_wrapper.EnumTypeWrapper(_PACKAGESTATUS)
FAILED = 0
REJECTED = 1
COMPLETE = 2
PROCESSING = 3
AWAITING_DECISION = 4


_SUBMITREQUEST = _descriptor.Descriptor(
    name="SubmitRequest",
    full_name="a3m.SubmitRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="a3m.SubmitRequest.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="url",
            full_name="a3m.SubmitRequest.url",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=18,
    serialized_end=60,
)


_SUBMITREPLY = _descriptor.Descriptor(
    name="SubmitReply",
    full_name="a3m.SubmitReply",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="a3m.SubmitReply.id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=62,
    serialized_end=87,
)


_STATUSREQUEST = _descriptor.Descriptor(
    name="StatusRequest",
    full_name="a3m.StatusRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="a3m.StatusRequest.id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=89,
    serialized_end=116,
)


_STATUSREPLY = _descriptor.Descriptor(
    name="StatusReply",
    full_name="a3m.StatusReply",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="status",
            full_name="a3m.StatusReply.status",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=118,
    serialized_end=167,
)

_STATUSREPLY.fields_by_name["status"].enum_type = _PACKAGESTATUS
DESCRIPTOR.message_types_by_name["SubmitRequest"] = _SUBMITREQUEST
DESCRIPTOR.message_types_by_name["SubmitReply"] = _SUBMITREPLY
DESCRIPTOR.message_types_by_name["StatusRequest"] = _STATUSREQUEST
DESCRIPTOR.message_types_by_name["StatusReply"] = _STATUSREPLY
DESCRIPTOR.enum_types_by_name["PackageStatus"] = _PACKAGESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubmitRequest = _reflection.GeneratedProtocolMessageType(
    "SubmitRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _SUBMITREQUEST,
        "__module__": "a3m_pb2"
        # @@protoc_insertion_point(class_scope:a3m.SubmitRequest)
    },
)
_sym_db.RegisterMessage(SubmitRequest)

SubmitReply = _reflection.GeneratedProtocolMessageType(
    "SubmitReply",
    (_message.Message,),
    {
        "DESCRIPTOR": _SUBMITREPLY,
        "__module__": "a3m_pb2"
        # @@protoc_insertion_point(class_scope:a3m.SubmitReply)
    },
)
_sym_db.RegisterMessage(SubmitReply)

StatusRequest = _reflection.GeneratedProtocolMessageType(
    "StatusRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _STATUSREQUEST,
        "__module__": "a3m_pb2"
        # @@protoc_insertion_point(class_scope:a3m.StatusRequest)
    },
)
_sym_db.RegisterMessage(StatusRequest)

StatusReply = _reflection.GeneratedProtocolMessageType(
    "StatusReply",
    (_message.Message,),
    {
        "DESCRIPTOR": _STATUSREPLY,
        "__module__": "a3m_pb2"
        # @@protoc_insertion_point(class_scope:a3m.StatusReply)
    },
)
_sym_db.RegisterMessage(StatusReply)


_TRANSFER = _descriptor.ServiceDescriptor(
    name="Transfer",
    full_name="a3m.Transfer",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=265,
    serialized_end=375,
    methods=[
        _descriptor.MethodDescriptor(
            name="Submit",
            full_name="a3m.Transfer.Submit",
            index=0,
            containing_service=None,
            input_type=_SUBMITREQUEST,
            output_type=_SUBMITREPLY,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="Status",
            full_name="a3m.Transfer.Status",
            index=1,
            containing_service=None,
            input_type=_STATUSREQUEST,
            output_type=_STATUSREPLY,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_TRANSFER)

DESCRIPTOR.services_by_name["Transfer"] = _TRANSFER

# @@protoc_insertion_point(module_scope)
