name: Build main image
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v2
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: sevein
        password: "${{ secrets.CR_PAT }}"
        image_name: artefactual-labs/a3m
        image_tag: main
        registry: ghcr.io
        build_extra_args: "--compress=true"
