name: Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
    - name: "Check out source code"
      uses: "actions/checkout@v4"
    - name: "Install Python"
      uses: "actions/setup-python@v5"
    - name: "Install dependencies"
      run: pip install setuptools wheel build
    - name: "Build"
      run: python -m build
    - name: "Publish"
      uses: pypa/gh-action-pypi-publish@release/v1

