name: Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
    - name: "Check out source code"
      uses: "actions/checkout@v4"
    - name: "Install Python"
      uses: "actions/setup-python@v5"
    - name: "Install dependencies"
      run: pip install setuptools wheel build
    - name: "Build"
      run: python -m build
    - name: "Publish"
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: Capture Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/artefactual-labs/a3m
        tags: |
          type=semver,pattern={{raw}}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
