name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment: release
    steps:
    - name: "Check out source code"
      uses: "actions/checkout@v4"
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v2
      with:
        enable-cache: true
        version: latest
    - name: Build package
      run: uv build
    - name: "Upload distribution packages to PyPI"
      uses: pypa/gh-action-pypi-publish@release/v1
  docker:
    runs-on: ubuntu-latest
    environment: release
    steps:
    - name: "Check out source code"
      uses: "actions/checkout@v4"
    - name: Capture Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/artefactual-labs/a3m
        tags: |
          type=semver,pattern={{raw}}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
